<?php

/**
 * @var \Hiberus\Garcia\Block\Index $block
 */
$alumnos = $block->getAlumno();

?>

<h2 class="title">Prueba</h2>

<?php

foreach($alumnos as $alumno) {

    ?>
    <ul>
        <li id="final">Nombre:<?= $alumno->getFirstName(); ?></li>
        <li id="final">Apellido: <?= $alumno->getLastName(); ?> </li>
        <?php
        if($alumno->getMark() >=5){  ?>
        <li id="aprobado">Nota:<?= $alumno->getMark(); ?></li>
        <?php
        }else{?>
            <li id="suspenso">Nota:<?= $alumno->getMark(); ?></li>
        <?php } ?>
    </ul>

<?php } ?>
<p id="cantidad"> Total de alumnos: <?= (count($alumnos)) ?> </p>
<?php
$notas=0;

foreach($alumnos as $alumno) {
    $notas+=$alumno->getMark();
}
$notasTotal= $notas/count($alumnos);
?>
<p id="cantidad"> Nota Media: <?= round($notasTotal,2) ?> </p>



